name: Build Images

on:
  push:
    branches:
      - main

env:
  BUILD_VERSION: v3.11.12-beagle

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Cross Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/go/src/yunion.io/x/cloudpods-operator \
            -w /go/src/yunion.io/x/cloudpods-operator \
            -e BUILD_VERSION=${{ env.BUILD_VERSION }} \
            registry.cn-qingdao.aliyuncs.com/wod/golang:1.24-alpine \
            bash .beagle/build.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Server AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.beagle/dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/onecloud:operator-${{ env.BUILD_VERSION }}-amd64
          build-args: |
            BASE=registry.cn-beijing.aliyuncs.com/yunionio/onecloud-base:v0.2
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}

      - name: Build Server ARM64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.beagle/dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/onecloud:operator-${{ env.BUILD_VERSION }}-arm64
          build-args: |
            BASE=registry.cn-beijing.aliyuncs.com/yunionio/onecloud-base:v0.2
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}

      - name: Create Server multi-arch manifest
        run: |
          docker buildx imagetools create -t registry.cn-qingdao.aliyuncs.com/wod/onecloud:operator-${{ env.BUILD_VERSION }} \
            registry.cn-qingdao.aliyuncs.com/wod/onecloud:operator-${{ env.BUILD_VERSION }}-amd64 \
            registry.cn-qingdao.aliyuncs.com/wod/onecloud:operator-${{ env.BUILD_VERSION }}-arm64
